
const magNum = [{
    name: '1/2019 – Rewolucje',
    url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje',
    articles: [{
        title: 'Emancypacja klasy chłopskiej w projekcie antyfeudalnej rewolucji księdza Piotra Ściegiennego. Perspektywa postkolonialna',
        author: 'Dr Jan Wasiewicz',
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/emancypacja-klasy-chlopskiej-w-projekcie-antyfeudalnej-rewolucji-ksiedza-piotra-sciegiennego-1',
    }, 
    {title: 'Obrazy nowego porządku. Powojenne przemiany społeczne w powieści Tadeusza Nowaka Diabły',
    author: 'Małgorzata Tarnowska',
    url: 'http://www.polisemia.com.pl/obrazy-nowego-porzadku'},
{title: 'Rewolucyjne gesty zerwania z doświadczeniem kolonialnym i porewolucyjne projekty tożsamościowe w powieściach Alaina Mabanckou',
author: 'Izabela Bryja', 
url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/rewolucyjne-gesty-zerwania-z-doswiadczeniem-kolonialnym'},
{title: 'Lot Hamleta. Dwie rewolucje w Hamlecie wtórym Romana Jaworskiego ',
author: 'Weronika Szulik', 
url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/lot-hamleta'},
{title: 'Psychoanaliza jako emancypacja. Pisma Ludwiki Karpińskiej oraz Stefanii   Zahorskiej',
author: 'Agnieszka Więckiewicz', 
url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/psychoanaliza-jako-emancypacja'},
{title: 'Za kulisami przeboju, czyli druga historia utworów z Konkursu Piosenki Eurowizji.     Rola (eurowizyjnej) muzyki w rewolucji',
author: 'Roksana Majewska', 
url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/za-kulisami-przeboju'},
{title: 'Od rewolucyjnych prawd do bolesnej bliskości. Instrukcja obsługi Czech według Jiříego Grušy [recenzja: Jiří Gruša, Czechy. Instrukcja obsługi (Česko – návod k použití), tłum. A.S. Jagodziński, Międzynarodowe Centrum w Krakowie, Kraków 2018].',
author: 'Magdalena Brodacka', 
url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/od-rewolucyjnych-prawd-do-bolesnej-bliskosci'},
{title: 'Jakim językiem mówią mieszkańcy paratopii? [recenzja: K. Kantner, Jak działać za pomocą słów? Proza Olgi Tokarczuk jako dyskurs krytyczny, Kraków 2019].',
author: 'Zofia Ulańska', 
url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2019-21---rewolucje/jakim-jezykiem-mowia-mieszkancy-paratopii'}]
}, {
    name: '2/2018 – Strach',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje',
	articles: [
        {title: 'Kobiecość a wampiryzm w literaturze grozy XVIII i XIX wieku',
        author: 'Anna Filipowicz (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/kobiecosc-a-wampiryzm-w-literaturze-grozy-xviii-i-xix-wieku'},
        {title: 'Strach przed działaniem i podmiot melancholijny. Obłomow Iwana Gonczarowa jako ontologiczny traktat o akcie i możności',
        author: 'Szymon Szeszuła (UAM)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/strach-przed-dzialaniem-i-podmiot-melancholijny'},
        {title: 'Widzę, widzę – austriackie lęki pod maską kina gatunku',
        author: 'Olga Wesołowska (UŁ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/widze-widze-czego-boi-sie-austria'},
        {title: 'Skorupa, kokon, bunkier, mur – strach przed nowoczesnym życiem. Beksiński, Bukowski, Gombrowicz, Waters',
        author: 'Błażej Szymankiewicz', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/skorupa-kokon-bunkier-mur'},
        {title: 'Proces jako widowisko. Performatywny wymiar spraw Danuty Siedzikówny, Wiktorii Rudnickiej, Antoniny Dziwisz i Olgi Hepnarovej',
        author: 'Aleksandra Kumala (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/proces-jako-widowisko'},
        {title: 'Historia, filologia, antropologia. Punkty wspólne? - dyskusja z prof. dr. hab. Krzysztofem Zamorskim, dr hab. Barbarą Klich-Kluczewską, dr. Jakubem Muchowskim i dr Marią Kobielską',
        author: 'Łukasz Łoziński', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/historia-filologia-antropologia-punkty-wspolne'},
        {title: 'Niech cień słońca upada na świat w pokoju – z Natalią Janus-Malewską rozmawia Martyna Jeleń',
        author: 'Martyna Jeleń, Natalia Jamus-Malewska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/niech-cien-slonca-upada-na-swiat-w-pokoju'},
        {title: 'Lęk w odcieniu retro [Recenzja książki: Z. Bauman, Retrotopia. Jak rządzi nami przeszłość, przeł. K. Lebek, Warszawa 2018]',
        author: 'Ewelina Śliwa (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/rewolucje/lek-w-odcieniu-retro'}
    ]
}, {
    name: '1/2018 – Przyszłość',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach',
	articles: [
        {title: 'Powrót z gwiazd – wizja idealnego społeczeństwa czy ogromna mistyfikacja?',
        author: 'Olga Gicala (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/powrot-z-gwiazd'},
        {title: 'Przyszłość niemożliwa – rewizja tożsamości nostalgicznej w twórczości Tadeusza Konwickiego',
        author: 'Aleksandra Siemieniuk (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/przyszlosc-niemozliwa'},
        {title: 'Kuratorskie sny w praktyce – konstruowanie alternatywnych wizji wspólnoty',
        author: 'Aleksandra Guja (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/kuratorskie-sny-w-praktyce'},
        {title: 'Trzy gwinee – wstępne rozpoznania fotograficznego projektu Virginii Woolf',
        author: 'Natalia Giemza (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/trzy-gwinee-wstepne-rozpoznania'},
        {title: 'Japoński duch, zachodnia technologia. O relacjach między przyszłością i przeszłością w J-Horrorze',
        author: 'Krzysztof Brenskott (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/japonski-duch-zachodnia-technologia'},
        {title: '(Nie)powinność wiersza – koncepcja poezji w utworze WIERSZ „POWINIEN” Krystyny Miłobędzkiej',
        author: 'Dorota Kołodziej (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/-nie-powinnosc-wiersza'},
        {title: 'Zwrócony w przyszłość. O meandrach kafkowskiego czasu [Recenzja książki: R. T. Gray, R. V. Gross, R. J. Goebel, C. Koelb, Franz Kafka. Encyklopedia, red. Ł. Musiał, tłum. J. Kozak, Warszawa 2017]',
        author: 'Magdalena Brodacka (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/zwrocony-w-przyszlosc'},
        {title: 'Kochać przeszłość dla przyszłości [Recenzja książki: K. Czyżewski, Małe centrum świata. Zapiski praktyka idei, Sejny/Krasnogruda 2017]',
        author: 'Anna Spiechowicz (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/Numer-22018-20---Strach/kochac-przeszlosc-dla-przyszlosci'}
    ]
}, {
    name: '2/2017 – Przeszłość',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc',
	articles: [
        {title: 'Obsesja historii, czyli przeszłość jako treść egzystencji. Stanisława Przybyszewska i Sprawa Dantona',
        author: 'Szymon Szeszuła (UAM)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/obsesja-historii-czyli-przeszlosc-jako-tresc-egzystencji'},
        {title: '(Her)storia – (His)terii',
        author: 'Syma Marta Al Azab-Malinowska (UAM)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/syma-marta-al-azab-malinowska-her-storia-his-terii'},
        {title: 'Proza Juliana Kawalca wobec „prześnionej rewolucji” (Ziemi przypisany, Tańczący jastrząb, Szara aureola)',
        author: 'Małgorzata Tarnowska (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/proza-juliana-kawalca-wobec-przesnionej-rewolucji'},
        {title: 'Opowieść podwójna. Jan Józef Szczepański w Ameryce Południowej',
        author: 'Barbara Fride (UG)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/opowiesc-podwojna'},
        {title: 'Figury miasta. Sny i kamienie Magdaleny Tulli',
        author: 'Dobrosława Korczyńska-Partyka (UG)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/figury-miasta'},
        {title: 'Postmodernistyczne postrzeganie przeszłości w powieści Ragtime E.L. Doctorowa',
        author: 'Paweł Łaniewski (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/postmodernistyczne-postrzeganie-przeszlosci'},
        {title: 'Przeszłość i wspominanie wobec problemu tożsamości narracyjnej w powieści Malina Ingeborg Bachmann',
        author: 'Julia Niedziejko (UAM)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/przeszlosc-i-wspominanie-wobec-problemu-tozsamosci-narracyjnej'},
        {title: 'Ruch i deterytorializacja. Stawanie się mniejszościowym Marii Komornickiej/Piotra Odmieńca Własta',
        author: 'Agnieszka Więckiewicz (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/ruch-i-deterytorializacja'},
        {title: 'Holocaust, którego nie sposób przeoczyć [Recenzja książki: Ślady Holocaustu w imaginarium kultury polskiej, Warszawa 2017]',
        author: 'Monika Gromala (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2017-przeszlosc/monika-gromala-holocaust-ktorego-nie-sposob-przeoczyc-recenzja-ksiazki-slady-holocaustu-w-imaginarium-kultury-polskiej-warszawa-2017'},
    ]
},{
    name: '1/2017 – Krzyk mody',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/krzyk-mody',
	articles: [
        {title: 'Frak i kontusz. Dwa projekty tożsamościowe polskich marek streetwearowych',
        author: 'Barbara Duchalska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/krzyk-mody/barbara-duchalska-frak-i-kontusz'},
        {title: 'W ogniu relacji: reportaż – moda czy głos współczesności?',
        author: 'Ewelina Śliwa', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/krzyk-mody/ewelina-sliwa-w-ogniu-relacji'},
        {title: 'Wearable technology art – nowe zjawisko w sztuce mediów? Wstępna charakterystyka nurtu na podstawie prac Atsuko Tanaki, Charlotte Moorman i Nam June Paika',
        author: 'Jakub Kłeczek', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/krzyk-mody/jakub-kleczek-wearable-technology-art'},
        {title: 'Myszka Miki w kimonie, czyli tradycyjny ubiór japoński w ponowoczesności',
        author: 'Agnieszka Kiejziewicz', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/krzyk-mody/agnieszka-kiejziewicz---myszka-miki-w-kimonie'}
    ]
},{
    name: '2/2016 – Fetysze',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2016-fetysze',
	articles: [
        {title: 'The cabinet of curiosities of Patti Smith: the space above the desk',
        author: 'Joanna Roś', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2016-fetysze/the-cabinet-of-curiosities-of-patti-smith'},
        {title: 'Kalafior i dystynkcja, czyli o tym, dlaczego o gustach się nie dyskutuje. Biesiada u hrabiny Kotłubaj Witolda Gombrowicza',
        author: 'Katarzyna Zielińska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2016-fetysze/kalafior-i-dystynkcja'},
        {title: 'Nogi w teatrze popularnym epoki wiktoriańskiej',
        author: 'Emilia Wieliczko-Paprota', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2016-fetysze/nogi-w-teatrze-popularnym-epoki-wiktorianskiej'},
    ]
},{
    name: '1/2016 – Wschód',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2016-15-wschod',
	articles: [
        {title: 'Wschód utracony, czyli mit Kresów w twórczości Tomasza Różyckiego',
        author: 'Elżbieta Pietluch', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2016-15-wschod/wschd-utracony-czyli-mit-kresw-w-twrczoci-tomasza-ryckiego'},
        {title: 'Meandry rosyjskiej duszy – tożsamość transkulturowa w twórczości Dmitrija Strelnikoffa',
        author: 'Anna Bugajna', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2016-15-wschod/meandry-rosyjskiej-duszy--tosamo-transkulturowa-w-twrczoci-dmitrija--strelnikoffa'},
        {title: 'Antropolog jako artysta, czyli tłumaczenia Slavs and Tatars',
        author: 'Gabriela Sułkowska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2016-15-wschod/antropolog-jako-artysta-czyli-tumaczenia-slavs-and-tatars'},
        {title: 'Rzeczpospolita obojga hegemonów. Postkolonialne perspektywy w badaniach nad sztuką ziem południowo-wschodnich dawnej Rzeczypospolitej',
        author: 'Piotr Policht', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2016-15-wschod/rzeczpospolita-obojga-hegemonw-postkolonialne-perspektywy-w-badaniach-nad-sztuk-ziem-poudniowo-wschodnich-dawnej-rzeczypospolitej'},
    ]
},{
    name: '1/2015 – Men studies',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies',
	articles: [
        {title: 'Chengdu, zapomnij o mnie dziś w nocy Muronga Xuecuna – kryzys wzorców męskości we współczesnych Chinach',
        author: 'Zofia Jakubów', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/chengdu-zapomnij-o-mnie-dzis-w-nocy-muronga-xuecuna-kryzys-wzorcow-meskosci-we-wspolczesnych-chinach'},
        {title: 'Maskulinizacja kobiety i demaskulinizacja mężczyzny – męskość w reportażach Martyny Wojciechowskiej Kobieta na krańcu świata',
        author: 'Monika Pruszkowska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/maskulinizacja-kobiety-i-demaskulinizacja-mezczyzny-meskosc-w-reportazach-martyny-wojciechowskiej-kobieta-na-krancu-swiata'},
        {title: '„Nikt nie rodzi się kobietą, lecz się nią staje”. Gra z tożsamością  i gra z tekstem służące do opisu transseksualnych doświadczeń mężczyzny w powieści Incognito Tibora Noé Kissa',
        author: 'Daniel Warmuz', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/-nikt-nie-rodzi-sie-kobieta-lecz-sie-nia-staje'},
        {title: 'Na styku kultur Wschodu i Zachodu: Komurasaki(…) Władysława Stanisława Reymonta a kontekst japoński (Remont Moriego Ōgaia)',
        author: 'Przemysław Górecki', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/na-styku-kultur-wschodu-i-zachodu-komurasaki-wladyslawa-stanislawa-reymonta-a-kontekst-japonski-remont-moriego-ogaia'},
        {title: 'Myślistwo jako praktyka męskości hegemonicznej na przykładzie powieści Soból i panna Józefa Weyssenhoffa',
        author: 'Justyna Rządeczko', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/myslistwo-jako-praktyka-meskosci-hegemonicznej-na-przykladzie-powiesci-sobol-i-panna-jozefa-weyssenhoffa'},
        {title: 'O zagrożeniach pornokracji. Przyczynek do historii refleksji antyfeministycznej',
        author: 'Grzegorz Zyzik', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/o-zagrozeniach-pornokracji-przyczynek-do-historii-refleksji-antyfeministycznej'},
        {title: 'Męskość według Kingi Dunin',
        author: 'Karol Petryszak', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-1-2015-14-men-studies/msko-wedug-kingi-dunin'}
    ]
},{
    name: '2/2014 – Transgraniczność',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13',
	articles: [
        {title: 'Między muzą a schematem. O Testamencie ’95 Jacka Kaczmarskiego',
        author: 'Kamila Czaja', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/Midzy-muz-a-schematem-O-Testamencie-95-Jacka-Kaczmarskiego'},
        {title: 'Wybrane aspekty twórczości Virginii Woolf w świetle filozofii kina Gillesa Deleuze’a',
        author: 'Adrian D. Kowalski', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/adrian-d-kowalski---wybrane-aspekty-twrczoci-virginii-woolf-w-wietle-filozofii-kina-gillesa-deleuzea'},
        {title: 'Sprawdzanie czterdziestu wieków historii, czyli próba analizy cyklu Wycieczka do Egiptu Mirona Białoszewskiego',
        author: 'Joanna Mazur', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/sprawdzanie-czterdziestu-wiekw-historii'},
        {title: 'Tożsamość jako wybór. Sytuacja pogranicza',
        author: 'Katarzyna Prałat', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/katarzyna-praat--tosamo-jako-wybr-sytuacja-pogranicza'},
        {title: 'Granice bohatera, granice biografii. O Twarzy Tuwima Piotra Matywieckiego',
        author: 'Marcin Romanowski ', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/granice-bohatera'},
        {title: 'Ubóstwo Kabylii. Wezwanie do socjopolitycznej sprawiedliwości czy etnografia nędzy? Rozważania nad relacjami Alberta Camusa z regionu kabylskiego',
        author: 'Joanna Roś', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/joanna-ro--ubstwo-kabylii-wezwanie-do-socjopolitycznej-sprawiedliwoci-czy-etnografia-ndzy-rozwaania-nad-relacjami-alberta-camusa-z-regionu-kabylskiego'},
        {title: 'Meandry (po)nowoczesnego przekraczania własnych granic – wezwanie i wyzwanie dla hermeneutyki',
        author: 'Katarzyna Szkaradnik ', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/szkaradnik-meandry-ponowoczesnego-przekraczania'},
        {title: 'Baśń reinterpretowana przez kino współczesne',
        author: 'Karolina Wawer', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/karolina-wawer--ba-reinterpretowana-przez-kino-wspczesne'},
        {title: 'Modlitwa organizmu: język wiary – język tekstu – język ciała. O esejach Jerzego Sosnowskiego',
        author: 'Martyna Wielewska-Baka', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/modlitwa-organizmu'},
        {title: 'Mówię do swego ciała: Ty ścierwo. Ciało jako abjekt i przedmiot koniecznej de(kon)strukcji w wybranych utworach Anny Świrszczyńskiej',
        author: 'Antoni Zając', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2014-13/mwi-do-swego-ciaa'}
    ]
},{
    name: '1/2014 – Kultura literacka, kultura audiowizualna',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/NUMER-12014-12',
	articles: [
        {title: 'Alegorie niemożliwe',
        author: 'Arkadiusz Półtorak (UJ)',
         url: 'http://www.polisemia.com.pl/numery-czasopisma/NUMER-12014-12/arkadiusz-ptorak--alegorie-niemoliwe'},
        {title: 'Memy – emblematy. Typowy Seba i Typowy Mirek',
        author: 'Łukasz Łoziński (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/NUMER-12014-12/ukasz-oziski--memy--emblematy-typowy-seba-i-typowy-mirek'},
        {title: 'Z daleka widok jest piękny? Problem z obrazem wsi w literaturze i filmie',
        author: 'Przemysław Zańko (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/NUMER-12014-12/przemysaw-zako--z-daleka-widok-jest-pikny-problem-z-obrazem-wsi-w-literaturze-i-filmie'},
        {title: 'Flâneur 2.0',
        author: 'Grzegorz Zyzik (Uniwersytet Opolski)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/NUMER-12014-12/grzegorz-zyzik--flneur-20'}
    ]
},{
    name: '2/2013 – Strategie krytyczne, kategoria gry',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2013-11',
	articles: [
        {title: 'Gra w nowoczesność czy gra nowoczesnością? Uwagi o Weselu hrabiego Orgaza Romana Jaworskiego',
        author: 'Aleksandra Szwagrzyk (UMK)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2013-11/gra-w-nowoczesnosc-czy-gra-nowoczesnoscia'},
        {title: 'Rytmu gra. Szkic(e) o Pannie Annie Bolesława Leśmiana. Analiza i interpretacja utworu',
        author: 'Łukasz Szeliga (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2013-11/rytmu-gra'},
        {title: 'Jak jest autor? Gra w (nie)obecność',
        author: 'Tomasz Dalasiński (UMK)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2013-11/gra-w-nie-obecnosc'},
        {title: 'Lektura campowa jako możliwość – przypadek Peleasa i Melizandy Claude’a Debussy’ego',
        author: 'Irena Chawrilska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2013-11/lektura-campowa-jako-moliwo'},
        {title: 'Gra muzyką, gra w muzykę. O niektórych aspektach ludycznych muzyki współczesnej',
        author: 'Marta Dziewanowska-Pachowska', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2013-11/gra-muzyk-gra-w-muzyk'}
    ]
},{
    name: '1/2013 – Materialność',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/12013',
	articles: [
        {title: 'Człowiek w kolekcji. Przypadek ludzkich monstrów',
        author: 'Maciej Skowera (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/czowiek-w-kolekcji'},
        {title: 'Materialność w literaturze ziem zachodnich. Huelle, Zagajewski, Chwin, Kornhauser, Tokarczuk',
        author: 'Łukasz Łoziński (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/materialno-w-literaturze-ziem-zachodnich'},
        {title: 'Ciało, cielesność i odcieleśnienie. Somatyka Sadu rozstajnego Bolesława Leśmiana',
        author: 'Michał Koza (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/ciao-cielesno-i-odcielenienie'},
        {title: 'Z powrotem do rzeczy (samych?) O projekcie hermeneutyki rzeczy na przykładzie pewnej wystawy muzealnej',
        author: 'Katarzyna Szkaradnik (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/z-powrotem-do-rzeczy-samych-o-projekcie-hermeneutyki-rzeczy-na-przykadzie-pewnej-wystawy-muzealnej'},
        {title: 'Od wideologii do oko-liczności - produkty firmy Apple w wizualnych przestrzeniach popkultury',
        author: 'Przemysław Dudziński (UWr)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/od-wideologii-do-oko-licznoci'},
        {title: 'Zbigniew Herbert i (nie)obecność wspomnienia. Próba lektury reograficznej',
        author: 'Marcin Romanowski (UG)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/zbigniew-herbert-i-nieobecno'},
        {title: 'Ryszard Schubert - Panna Lilianka. Przyjemność (do)czytania',
        author: 'Sylwia Wojtysiak (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/12013/ryszard-schubert---panna-lilianka'}
    ]
},{
    name: '2/2012 – Filozofia literatury, filozofia w literaturze',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9',
	articles: [
        {title: 'Doświadczenie egzystencjalne a inspiracje twórczości literackiej, na przykładzie teorii literatury Jean Paul Sartre’a',
        author: 'Joanna Roś (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/dowiadczenie-egzystencjalne'},
        {title: 'Sześć postaci powieściowych w poszukiwaniu Percivala. O problematyce podmiotowości w Falach Virginii Woolf',
        author: 'Michał Koza (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/sze-postaci-powieciowych-w-poszukiwaniu-percivala'},
        {title: 'Skazanie na pustkę? Między egzystencjalistyczną (bez)wolnością a hermeneutycznym wyzwoleniem w prozie Magdaleny Tulli',
        author: 'Katarzyna Szkaradnik (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/skazanie-na-pustk'},
        {title: 'Psychologia i filozofia terroryzmu według Dziejów jednego pocisku Andrzeja Struga',
        author: 'Łukasz Łoziński (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/psychologia-i-filozofia-terroryzmu-wedug-dziejw-jednego-pocisku-andrzeja-struga'},
        {title: 'Wykład profesora Mmaa Stefana Themersona jako dzieło oparte na wątpieniu',
        author: 'Katarzyna Gil (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/wykad-profesora-mmaa-stefana-themersona-jako-dzieo-oparte-na-wtpieniu'},
        {title: 'Esej o metodzie, esej jako metoda. Problematyka epistemologiczna w Minima Moralia Theodora W. Adorno',
        author: 'Paweł Pijanowski (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/esej-o-metodzie-esej-jako-metoda-problematyka-epistemologiczna-w-minima-moralia-theodora-w-adorno'},
        {title: 'Motywy ontologii i epistemologii tomistycznej w ostatnich tomach poezji Czesława Miłosza',
        author: 'Michał Chęciński (UWr)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/motywy-ontologii-i-epistemologii-tomistycznej'},
        {title: 'Ksenotopografia fikcji w świetle późnej fenomenologii Bernharda Waldenfelsa',
        author: 'Krzysztof M. Maj (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2012-9/ksenotopografia-fikcji'}
    ]
},{
    name: '1/2012 – Gdzie jest postmodernizm? (II)',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8',
	articles: [
        {title: 'Słowo jedno znaczące? Problem podmiotowości ponowoczesnej w dziele Czesława Miłosza',
        author: 'Paweł Grad (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/sowo-jedno-znaczce'},
        {title: 'Post-slasher, czyli postmodernistyczny wariant slashera',
        author: 'Amelia Wichowicz (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/post-slasher'},
        {title: 'Kino (ciągle) mówi o kinie. Filmy autotematyczne ostatniego dziesięciolecia',
        author: 'Paweł Biliński (UG)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/kino-cigle-mwi-o-kinie'},
        {title: 'Między teorią symulakrum a portretem. Portrety Anety Grzeszykowskiej i Portrety Thomasa Ruffa',
        author: 'Ewelina Mykicka (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/midzy-teori-symulakrum-a-portretem-portrety-anety-grzeszykowskiej-i-portrety-thomasa-ruffa'},
        {title: 'Depresja dyskursu, czyli między sublimacją a paranoją. Modernizm i postmodernizm w świetle psychoanalitycznej teorii Julii Kristevej',
        author: 'Marcin Januszewski (UG)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/depresja-dyskursu'},
        {title: 'Twórczość Brunona Schulza jako krytyczne przewartościowanie „rzeczywistości”',
        author: 'Dominik Antonik (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/twrczo-brunona-schulza-jako-krytyczne-przewartociowanie-rzeczywistoci'},
        {title: 'Pamięć Holokaustu. Forma Federmana',
        author: 'Katarzyna Gil (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/pami-holokaustu'},
        {title: 'Czy tak zwana powieść postmodernistyczna jest próbą odpowiedzi na tak zwany kryzys powieści?',
        author: 'Martyna Wielewska (UG)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/czy-tak-zwana-powie'},
        {title: 'Depesze i migawki z Międzystrefy. Nagi Lunch Williama Burroughsa a Nagi Lunch Davida Cronenberga',
        author: 'Michał Lesiak (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/migawki-z-midzystrefy'},
        {title: 'Anurag Kashyap – autor w Bollywood?',
        author: 'Paweł Świerczek (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12012-8/anurag-kashyap--autor-w-bollywood'},
    ]
},{
    name: '3/2011 – Gdzie jest postmodernizm? (I)',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7',
	articles: [
        {title: 'Nie tylko Pamuk',
        author: 'Piotr Kawulok (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/nie-tylko-pamuk'},
        {title: 'Sprawa Akō a Chūshingura, fakty a przedstawienia: Filmowe (re)interpretacje historii 47 wiernych roninów',
        author: 'Dawid Głownia (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/sprawa-ako'},
        {title: 'Opowiadać znaczy tworzyć siebie. Postmodernistyczne strategie w filmie Dym Paula Austera i Wayne’a Wanga',
        author: 'Aneta Jałocha (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/opowiadac-znaczy-tworzyc-siebie'},
        {title: '„Jeśli jestem...” - podmiot słaby w prozie Magdaleny Tulli',
        author: 'Michał Sowiński (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/jesli-jestem'},
        {title: 'Podmiot tekstowy w Przezroczystości Marka Bieńczyka',
        author: 'Olga Szmidt (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/podmiot-tekstowy'},
        {title: 'Atak śniegu! – polityczność natury w sztuce Agnieszki Kurant',
        author: 'Karolina Plinta (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/atak-sniegu'},
        {title: '(Post)feministyczne trawestacje. O dziewczyńskich zabawach artystek ostatniej dekady',
        author: 'Marta Świetlik (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/postfeministyczne-trawestacja'},
        {title: 'Laboratorium antropologiczne. Postać metafikcyjna w powieści Mantissa Johna Fowlesa',
        author: 'Maciej Jakubowiak (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/laboratorium-antropologiczne'},
        {title: 'Milan Kundera jako debiutujący prozaik – (post)modernista?',
        author: 'Olga Słowik (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2011-7/milan-kundera-jako-debiutujacy-prozaik'}
    ]
},{
    name: '2/2011 – Wielokulturowość, etniczność i narodowość w literaturze',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2011-6',
	articles: [
        {title: 'Doświadczenie wojny i problem jej reprezentacji w twórczości Jeana Hatzfelda',
        author: 'Edyta Żyrek (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2011-6/doswiadczenie-wojny'},
        {title: 'Mit lub milczenie. Zbrodnia katyńska w polskiej pamięci kulturowej po 1989 r.',
        author: 'Maria Kobielska (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2011-6/mit-lub-milczenie'},
        {title: 'Czarna żółć. Melancholia w powieści Black Bazar Alaina Mabanckou',
        author: 'Olga Szmidt (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2011-6/czarna-zolc'},
        {title: 'Demonologia Czesława Miłosza. Dolina Issy w perspektywie etnologicznej',
        author: 'Łukasz Łoziński (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2011-6/demonologia'},
        {title: 'Święty odmieniec. O bohaterach utworów Włodzimierza Pawluczuka',
        author: 'Katarzyna Werstak (IBL PAN)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2011-6/swiety-odmieniec'}
    ]
},{
    name: '1/2011 – Literatura popularna, masowa i drugorzędna',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12011-5',
	articles: [
        {title: 'Wysypisko popkultury. Balladyny i romanse Ignacego Karpowicza',
        author: 'Monika Sakowska (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-12011-5/numer-1-2011-5/wysypisko-popkultury'}
    ]
},{
    name: '4/2010 – Strategie awangardowe w poezji',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4',
	articles: [
        {title: 'Andrzej Sosnowski - poeta społecznie niedostępny',
        author: 'Danuta Turczyńska (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/andrzej-sosnowski-poeta-spolecznie-niedostepny'},
        {title: '„Czy jestem poetą ponowoczesnym?” Oceany Andrzeja Sosnowskiego jako próba odpowiedzi',
        author: 'Michalina Kmiecik (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/-czy-jestem-poeta-ponowoczesnym-oceany-andrzeja-sosnowskiego-jako-proba-odpowiedzi'},
        {title: 'Co eskortuje Konwój? Andrzej Sosnowski i radykalne doświadczenie pisma',
        author: 'Adam Błażejewicz (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/co-eskortuje-konwoj-andrzej-sosnowski-i-radykalne-doswiadczenie-pisma'},
        {title: 'Kumpelska awangarda. Literatura jako narzędzie emancypacji',
        author: 'Jan Kapela (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/kumpelska-awangarda-literatura-jako-narzedzie-emancypacji'},
        {title: 'Odtrącona wyobraźnia. Polska poezja zamiast surrealizmu',
        author: 'Jakub Kornhauser (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/odtracona-wyobraznia-polska-poezja-zamiast-surrealizmu'},
        {title: 'Nowy Ikar a poetystyczne początki poezji politematycznej w Czechosłowacji',
        author: 'Olga Słowik (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/nowy-ikar-a-poetystyczne-poczatki-poezji-politematycznej-w-czechoslowacji'},
        {title: 'Sztuka (wielo)znaku. Humor w poezji konkretnej (na przykładzie utworów Pawła Majerskiego, Piotra Majdanika i innych)',
        author: 'Izabela Mikrut (UŚ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/sztuka-wielo-znaku-humor-w-poezji-konkretnej-na-przykladzie-utworow-pawla-majerskiego-i-piotra-majdanika'},
        {title: 'Mięso w bibliotece, czyli życie i literatura w Retardacji Agnieszki Kuciak',
        author: 'Ewelina Pytel (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-4-2010-4/mieso-w-bibliotece-czyli-zycie-i-literatura-w-retardacji-agnieszki-kuciak'},
    ]
},{
    name: '3/2010 – Polityczność literatury (II – literatura polska)',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2010-3',
	articles: [
        {title: 'Zwrot (nie)polityczny, albo: Polityczna śmierć Michała Witkowskiego?',
        author: 'Jakub Szestowicki (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2010-3/zwrot-nie-polityczny-albo-polityczna-smierc-michala-witkowskiego'},
        {title: 'Dukaj i krytycy robią stan wojenny. O Wrońcu i wokół Wrońca',
        author: 'Piotr Sterczewski (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2010-3/dukaj-i-krytycy-robia-stan-wojenny-o-wroncu-i-wokol-wronca'},
        {title: 'Wolny rynek słów? Reguły i ekonomia w polskiej  poezji awangardowej.',
        author: 'Agnieszka Jeżyk (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2010-3/wolny-rynek-slow-reguly-ekonomii-w-polskiej-poezji-awangardowej'},
        {title: 'Niesłychany występ żydowskiego nihilisty. Do prostego człowieka Juliana Tuwima i prasowe echa jego publikacji.',
        author: 'Krzysztof Niewiadomski (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2010-3/nieslychany-wystep-zydowskiego-nihilisty-do-prostego-czlowieka-juliana-tuwima-i-prasowe-echa-jego-publikacji'},
        {title: 'Niczego o nas nie ma w konstytucji. O strategiach (anty)politycznych w poezji Marcina Świetlickiego w kontekście twórczości poetów brulionu',
        author: 'Magdalena Kunz (UJ) ', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-3-2010-3/niczego-o-nas-nie-ma-w-konstytucji-o-strategiach-anty-politycznych-w-poezji-marcina-swietlickiego-w-kontekscie-tworczosci-poetow-brulionu'},
    ]
},{
    name: '2/2010 – Polityczność literatury (I – literatura obca i teoria)',
	url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2',
	articles: [
        {title: 'Niewinne wiersze dla dzieci czy propaganda od najmłodszych lat? O twórczości Siergieja Michałkowa',
        author: 'Anna Wrońska (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/niewinne-wiersze-dla-dzieci-czy-propaganda-od-najmlodszych-lat'},
        {title: 'Butelka wódki albo kilo soli... polski przekład księgi pamięci gminy żydowskiej w Szczekocinach',
        author: 'Marek Tuszewicki (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/butelka-wodki-albo-kilo-soli'},
        {title: '',
        author: '', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/niewinne-wiersze-dla-dzieci-czy-propaganda-od-najmlodszych-lat'},
        {title: 'Król kłania się i zabija Herty Müller - doświadczenie języka jako sposobu obrony przed dyktaturą',
        author: 'Ryszard Wołosiuk (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/krol-klania-sie-i-zabija'},
        {title: ' Trud autobiografii. Konstruowanie tożsamości w rzeczywistości politycznej. Chłopięce lata. Sceny z prowincjonalnego życia Johna Maxwella Coetzee\'ego',
        author: 'Olga Szmidt (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/trud-autobiografii-konstruowanie-tozsamosci-w-rzeczywistosci-politycznej'},
        {title: 'Teoria wobec jednostkowego spotkania z tekstem, czyli do czego służy filozofia interpretacji',
        author: 'Dominik Antonik (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/teoria-wobec-jednostkowego-spotkania-z-tekstem-czyli-do-czego-sluzy-filozofia-interpretacji'},
        {title: 'Przekład literacki - manipulacja: refrakcja i instytucja patronatu według Andre Lefevere\'a i Manipulation School',
        author: 'Katarzyna Szymańska (UW)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/przeklad-literacki---manipulacja'},
        {title: 'Etyka czy polityka? Ku nowym paradygmatom lektury',
        author: 'Paweł Rams (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/etyka-czy-polityka-ku-nowym-paradygmatom-lektury'},
        {title: 'Hermeneutyka myśli prześladowanej: przypadek Leo Straussa',
        author: 'Jakub Chmielniak (UJ)', 
        url: 'http://www.polisemia.com.pl/numery-czasopisma/numer-2-2010-2/hermeneutyka-mysli-przesladowanej-przypadek-leo-straussa'},
    ]
}]


export { magNum }